### PR TITLE
Fixed Auth Hashing

### PR DESCRIPTION
**Pull request by base0010**
Buffers Buffer Objects and spaces getting passed into hashing function
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by base0010** [comment]
@rhlsthrm

**Comment by rhlsthrm** [comment]
Great stuff @base0010. I think the other change will have to be made inside modules/client, which does the front end auth, right?

**Comment by base0010** [comment]
Yeah that commit includes the change to AuthenticationClient (Covers MetaMask)  autosigner dosen't append the ETH message prefix afaik.

**Comment by ArjunBhuptani** [comment]
@rhlsthrm Can we include this fix in the current sprint? It might mean tweaking the signer service again but we should do it BEFORE users generate sigs that hold funds.

**Comment by rhlsthrm** [comment]
Hey @base0010, this breaks our current clients with the spaces removed. I believe your issue should be fixed by this commit: https://github.com/ConnextProject/indra/commit/ff10cb934c6afecb80036ff5d70e4c159df8e57e, but you'll have to change your client to add the spaces back in.

**Comment by base0010** [comment]
@rhlsthrm the spaces shouldn't be a problem to add back, def want to be explicit about that in the documentation going forward. I'll double check that this hashes the correct data with my client.

**Pull request merged**
